DA: false
LPN: true
batchsize: 4
block: 4
color_jitter: false
data_dir: /media/user/1AD07E595CCB2146/zb/datasets/University-Release/train
droprate: 0.75
erasing_p: 0
extra_Google: false
fp16: false
gpu_ids: '0'
h: 512
lr: 0.001
moving_avg: 1.0
name: LPN+Pvt_v2+drn+two_branch-3-512x512
nclasses: 701
pad: 10
pool: avg
resume: false
share: true
stride: 1
train_all: false
use_NAS: false
use_dense: false
views: 3
w: 512
warm_epoch: 0
